apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-manipulator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-manipulator
subjects:
- kind: ServiceAccount
  name: {{ include "pod-lifetime-limiter.serviceAccountName" . }}
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-manipulator
  apiGroup: rbac.authorization.k8s.io
